version: 0.2

env:
  variables:
    FLUTTER_VERSION: "3.38.5"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - export FLUTTER_DIR="$HOME/flutter"
      - git clone https://github.com/flutter/flutter.git --depth 1 --branch $FLUTTER_VERSION $FLUTTER_DIR
      - export PATH="$PATH:$FLUTTER_DIR/bin"
      - flutter doctor
  build:
    commands:
      - echo "Build Flutter Website..."
      - cd src/app
      - |
        flutter build web \
          --dart-define=COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID \
          --dart-define=COGNITO_APP_CLIENT_ID=$COGNITO_CLIENT_ID \
          --dart-define=COGNITO_REGION=$COGNITO_REGION \
          --dart-define=FLASHCARDS_API_ENDPOINT=$FLASHCARDS_API_ENDPOINT \
          --dart-define=FLASHCARDS_API_REGION=$FLASHCARDS_API_REGION
  post_build:
    commands:
      - echo "Deploying to $WEBSITE_BUCKET..."
      - aws s3 sync build/web s3://$WEBSITE_BUCKET --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
